name: clubs_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_database: ^10.2.3
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2
  firebase_core_web: ^2.6.0

  flutter_local_notifications: ^13.0.0 #------
  url_launcher: ^6.0.20 #-----
  image_picker: ^0.8.4+8 #-----
  #flutter_background_service: ^2.4.6 #------
  #flutter_inappwebview: 5.4.4
  http: any
  shared_preferences: ^2.0.15 #ios Storage location : NSUserDefaults
  fluttertoast: ^8.0.8
  geocoding: ^2.0.2 # convert address to latlng
  intl_phone_number_input: ^0.7.0+2
  awesome_dialog: ^3.0.2
  line_icons: ^2.0.3
  google_fonts: ^4.0.4
  path_provider: any
  open_file: any
  animated_text_kit: any
  intl: any
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  collection: ^1.15.0

  pinch_zoom: ^1.0.0
  font_awesome_flutter: ^10.4.0 #icons
  email_validator: '^2.1.16'
  custom_map_markers: ^0.0.1
  dropdown_button2: ^1.6.3 # used for item options dropdown
  introduction_screen: any
  youtube_player_flutter: ^8.1.0
  settings_ui: ^2.0.2
  flutter_typeahead: ^4.0.0 # for textField in appbar
  responsive_sizer: ^3.1.0
  tutorial_coach_mark: ^1.2.6
  cached_network_image: any #  with downloading image
  shimmer: ^2.0.0
  country_pickers: ^2.0.0

  fancy_shimmer_image: ^2.0.2
  alarm: any
  auto_size_text: ^3.0.0
  timezone: any

  flutter_facebook_auth: ^6.0.3
  numberpicker: ^2.1.2
  flutter_animated_dialog: any
  flutter_advanced_drawer: ^1.3.5
  pdf: ^3.10.4
  printing: any
  connectivity_plus: ^4.0.1
  fl_chart: ^0.63.0
  flutter_launcher_icons: ^0.13.1
  loader_overlay: any
  loading_animation_widget: any
  flutter_spinkit: any
  flutter_easyloading: ^3.0.5
  loading_indicator: ^3.1.0
  easy_date_timeline: ^1.0.5
  flutter_swipe_action_cell: ^3.1.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_animations: ^1.1.1
  custom_refresh_indicator: ^3.0.0
  flutter_hooks: ^0.20.5
  animations: ^2.0.0
  json_annotation: ^4.8.1
  geopoint: ^1.0.0
  random_avatar: ^0.0.8
  avatar_glow: ^3.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
